version: "3.8"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ~/Documents/STUDIA/As/db_files:/var/lib/mysql
