version: "3.8"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ~/Documents/STUDIA/As/db_files:/var/lib/mysql

#  backend:
#    build: .
#    ports:
#      - "5000:5000"
#    depends_on:
#      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    depends_on:
      - mysql
